//double* cross_product(double[],double[]);
//double bending_energy();
//double bond_harmonic_energy();
//double bond_length (int ,int );
//double backbone_length(int);
//double avg_hgt();
//double avg_hgt_sq();
double avg_pos();
//int initialize();
//int sum_hgt_node();
//int avg_hgt_node(int);
//int hgt_profile();
//int avg_hgt_profile(FILE *,int);
//int width_hgt(int);
//int print_width(FILE *);
